In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

# Sửa đường dẫn này nếu bạn để file ở chỗ khác
MESSAGES_JSONL_PATH = Path(r"C:\Users\Admin\Chatbot_answering_vietnamese_history\Dataset\Pack1\bach_dang_ngo_quyen_rag_sft_messages_20.jsonl")

print("File path:", MESSAGES_JSONL_PATH)
print("Exists:", MESSAGES_JSONL_PATH.exists())

if MESSAGES_JSONL_PATH.exists():
    print("Size:", f"{MESSAGES_JSONL_PATH.stat().st_size / 1024:.2f} KB")
else:
    print("Không tìm thấy file. Hãy kiểm tra lại đường dẫn.")

File path: C:\Users\Admin\Chatbot_answering_vietnamese_history\Dataset\Pack1\bach_dang_ngo_quyen_rag_sft_messages_20.jsonl
Exists: True
Size: 156.84 KB

In [2]:
records = []
bad_lines = []

with open(MESSAGES_JSONL_PATH, "r", encoding="utf-8") as f:
    for line_no, line in enumerate(f, start=1):
        line = line.strip()

        if not line:
            continue

        try:
            obj = json.loads(line)
            records.append(obj)
        except Exception as e:
            bad_lines.append({
                "line_no": line_no,
                "error": str(e),
                "preview": line[:300],
            })

print("Đọc được records:", len(records))
print("Bad lines:", len(bad_lines))

if bad_lines:
    display(pd.DataFrame(bad_lines).head(10))

Đọc được records: 20
Bad lines: 0

In [3]:
schema_errors = []

for i, r in enumerate(records):
    sample_id = r.get("id", f"row_{i}")

    if "messages" not in r:
        schema_errors.append({
            "row": i,
            "id": sample_id,
            "error": "Thiếu field messages",
        })
        continue

    messages = r["messages"]

    if not isinstance(messages, list):
        schema_errors.append({
            "row": i,
            "id": sample_id,
            "error": "messages không phải list",
        })
        continue

    if len(messages) < 2:
        schema_errors.append({
            "row": i,
            "id": sample_id,
            "error": "messages có ít hơn 2 message",
        })
        continue

    for j, msg in enumerate(messages):
        if not isinstance(msg, dict):
            schema_errors.append({
                "row": i,
                "id": sample_id,
                "error": f"message {j} không phải dict",
            })
            continue

        if "role" not in msg:
            schema_errors.append({
                "row": i,
                "id": sample_id,
                "error": f"message {j} thiếu role",
            })

        if "content" not in msg:
            schema_errors.append({
                "row": i,
                "id": sample_id,
                "error": f"message {j} thiếu content",
            })

        if msg.get("role") not in ["system", "user", "assistant"]:
            schema_errors.append({
                "row": i,
                "id": sample_id,
                "error": f"message {j} có role lạ: {msg.get('role')}",
            })

print("Schema errors:", len(schema_errors))

if schema_errors:
    display(pd.DataFrame(schema_errors).head(20))
else:
    print("OK: file messages JSONL hợp lệ để train dạng chat SFT.")

Schema errors: 0
OK: file messages JSONL hợp lệ để train dạng chat SFT.

In [4]:
rows = []

for r in records:
    messages = r.get("messages", [])

    user_msg = ""
    assistant_msg = ""

    for m in messages:
        if m.get("role") == "user":
            user_msg = m.get("content", "")
        elif m.get("role") == "assistant":
            assistant_msg = m.get("content", "")

    rows.append({
        "id": r.get("id", ""),
        "type": r.get("type", ""),
        "num_messages": len(messages),
        "user_preview": user_msg[:700],
        "assistant_preview": assistant_msg[:700],
    })

df_msg = pd.DataFrame(rows)

print("Shape:", df_msg.shape)
display(df_msg)

Shape: (20, 5)

,id,type,num_messages,user_preview,assistant_preview
0,sample_0001,noisy_context,2,Câu hỏi:\nChiến thắng Bạch Đằng năm 938 gắn vớ...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
1,sample_0002,noisy_context,2,Câu hỏi:\nBạch Đằng năm 938 đã đánh bại quân x...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
2,sample_0003,noisy_context,2,Câu hỏi:\nÝ nghĩa lịch sử của chiến thắng Bạch...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
3,sample_0004,noisy_context,2,"Câu hỏi:\nSau chiến thắng Bạch Đằng, Ngô Quyền...",Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
4,sample_0005,noisy_context,2,Câu hỏi:\nKiều Công Tiễn có vai trò gì trong b...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0001_...
5,sample_0006,noisy_context,2,Câu hỏi:\nNgô Quyền đã dùng kế gì để đánh quân...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0002_...
6,sample_0007,noisy_context,2,Câu hỏi:\nLưu Hoằng Tháo trong trận Bạch Đằng ...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0002_...
7,sample_0008,noisy_context,2,Câu hỏi:\nNgô Quyền xưng vương và đóng đô ở đâ...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0001_...
8,sample_0009,noisy_context,2,Câu hỏi:\nVì sao Ngô Quyền không chọn Đại La l...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0003_...
9,sample_0010,noisy_context,2,Câu hỏi:\nTrận Bạch Đằng năm 1288 do ai chỉ hu...,Nguồn được dùng: [hf_wikipedia_trận_bạch_đằng_...
10,sample_0011,noisy_context,2,Câu hỏi:\nBạch Đằng năm 1288 khác Bạch Đằng nă...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
11,sample_0012,noisy_context,2,Câu hỏi:\nChiến thắng Bạch Đằng năm 1288 có va...,Nguồn được dùng: [hf_wikipedia_trận_bạch_đằng_...
12,sample_0013,noisy_context,2,Câu hỏi:\nNhững di tích tưởng niệm Ngô Quyền t...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0006_...
13,sample_0014,grounded_qa,2,Câu hỏi:\nNgô Quyền sinh và mất vào thời gian ...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
14,sample_0015,grounded_qa,2,Câu hỏi:\nNgô Quyền trị vì trong khoảng thời g...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
15,sample_0016,grounded_qa,2,"Câu hỏi:\nTheo tài liệu, Dương Đình Nghệ có qu...",Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...
16,sample_0017,grounded_qa,2,Câu hỏi:\nPhan Bội Châu tôn vinh Ngô Quyền như...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0004_...
17,sample_0018,insufficient_context,2,Câu hỏi:\nNgô Quyền có chính sách thuế cụ thể ...,Nguồn được dùng: []\n\nTrả lời:\nTài liệu được...
18,sample_0019,insufficient_context,2,Câu hỏi:\nTrận Bạch Đằng năm 938 có chính xác ...,Nguồn được dùng: []\n\nTrả lời:\nTài liệu được...
19,sample_0020,false_premise,2,Câu hỏi:\nTrần Hưng Đạo đã đánh bại quân Nam H...,Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_...

In [5]:
idx = 0  # đổi số này để xem sample khác

sample = records[idx]

print("=" * 120)
print("ID:", sample.get("id"))
print("TYPE:", sample.get("type"))
print("=" * 120)

for m in sample["messages"]:
    print("\n" + "-" * 120)
    print("ROLE:", m["role"])
    print("-" * 120)
    print(m["content"])

========================================================================================================================
ID: sample_0001
TYPE: noisy_context
========================================================================================================================

------------------------------------------------------------------------------------------------------------------------
ROLE: user
------------------------------------------------------------------------------------------------------------------------
Câu hỏi:
Chiến thắng Bạch Đằng năm 938 gắn với nhân vật nào?

Tài liệu tham khảo:
[hf_wikipedia_ngô_quyền_0000_af223d790816] Ngô Quyền
Ngô Quyền (; 17 tháng 4 năm 898 – 14 tháng 2 năm 944), còn được biết đến với tên gọi Tiền Ngô Vương () là vị vua đầu tiên của nhà Ngô trong lịch sử Việt Nam. Năm 938, ông là người lãnh đạo nhân dân đánh bại quân Nam Hán trong trận Bạch Đằng, chính thức kết thúc gần một ngàn năm Bắc thuộc, mở ra một thời kì độc lập lâu dài của Việt Nam. Sau chiến thắng này, ông lên ngôi vua, lập ra nhà Ngô, trị vì từ năm 939 đến năm 944. Ngô Quyền nằm trong danh sách mười bốn anh hùng dân tộc Việt Nam. Phan Bội Châu xem ông là vị Tổ Trung hưng của Việt Nam. Thân thế Ngô Quyền sinh ngày 12 tháng 3 năm Đinh Tỵ (17 tháng 4 năm 898) trong một dòng họ hào trưởng có thế lực. Cha là Ngô Mân làm chức châu mục Đường Lâm. Ngô Quyền được sử sách mô tả là bậc anh hùng tuấn kiệt, "có trí dũng". Theo Đại Việt Sử ký Toàn thư: Sự nghiệp Bối cảnh Thời bấy giờ nhà Đường ở Trung Quốc cai trị nước Việt. Từ giữa thế kỷ IX, nhà Đường phải đối phó với hai biến cố lớn là nông dân khởi nghĩa và phiên trấn cát cứ. Năm 907, nhà Đường mất, Chu Ôn lập nên nhà Hậu Lương, bắt đầu cuộc loạn Ngũ Đại, sử Trung Quốc gọi là Ngũ đại Thập quốc. Ở miền Nam Trung Quốc, Tiết độ sứ Quảng Châu là Lưu Nham đã cát cứ và dựng nước Nam Hán. Năm 905, nhân việc nhà Đường có loạn, một thổ hào người Việt là Khúc Thừa Dụ nổi lên đánh đuổi người Trung Quốc, chiếm giữ phủ thành, xưng là Tiết độ sứ. Năm 907, Khúc Thừa Dụ chết, con là Khúc Hạo lên thay. Khúc Hạo sai con là Khúc Thừa Mỹ làm Hoan hảo sứ sang dò xét nhà Nam Hán. Năm 917, Khúc Hạo chết, Khúc Thừa Mỹ lên thay, cho người sang nhà Lương lĩnh tiết việt, muốn lợi dụng sự mâu thuẫn giữa nước Lương và Nam Hán để củng cố sự nghiệp tự cường của mình. Vua Nam Hán là Lưu Cung tức giận, xua quân chiếm cứ Giao Chỉ. Năm 930, tướng Nam Hán Lý Khắc Chính đem binh đánh, bắt được Khúc Thừa Mỹ, Lý Khắc Chính lưu lại Giao Chỉ. Một hào trưởng người Ái Châu (thuộc Thanh Hóa ngày nay) là Dương Đình Nghệ nuôi 3000 con nuôi, mưu đồ khôi phục. Ngô Quyền lớn lên làm nha tướng cho Dương Đình Nghệ, được Dương Đình Nghệ gả con gái cho và giao quyền cai quản Ái châu, đất bản bộ của họ Dương. Năm 931, Dương Đình Nghệ phát binh từ Thanh Hóa ra Bắc đánh đuổi quân Nam Hán, đánh bại Lý Tiến và quân cứu viện ... [ĐÃ CẮT BỚT]

[hf_wikipedia_trận_bạch_đằng_1288_0000_9e0fa2aca313] Trận Bạch Đằng (1288)
Trận Bạch Đằng năm 1288 xảy ra trên sông Bạch Đằng thuộc đất Đại Việt, là một trận đánh quan trọng trong các cuộc kháng chiến chống Nguyên Mông trong lịch sử Việt Nam. Đây là chiến thắng vẻ vang của quân Đại Việt do Quốc công Tiết chế Trần Hưng Đạo cùng với Thái thượng hoàng Trần Thánh Tông và vua Trần Nhân Tông chỉ huy trước quân xâm lược Nguyên Mông. Quân Nguyên bị thiệt hại vô cùng nặng (với khoảng hơn 4 vạn quân sĩ bị loại khỏi vòng chiến), và nhiều tướng Nguyên trong đó có cả Ô Mã Nhi, Phạm Nhàn và Phàn Tiếp cũng bị bắt sống và dâng lên Thượng hoàng Thánh Tông. Ngoài ra, có những 400 chiến thuyền của quân Nguyên rơi vào tay quân Trần. Đại thắng trên sông Bạch Đằng được xem là trận thủy chiến lớn nhất trong lịch sử Việt Nam, và là thắng lợi tiêu biểu nhất của Đại Việt trong ba cuộc kháng chiến chống quân xâm lược Nguyên-Mông. Đại thắng này là một chiến quả của kế cắm cọc trên sông Bạch Đằng của Hưng Đạo Vương, mở đầu với việc quân sĩ của ông lừa được địch vào trận địa cọc nhân triều rút. Quân Nguyên vấp phải sự chiến đấu mãnh liệt của quân Thánh Dực dưới quyền Nguyễn Khoái (Bình chương Áo Lỗ Xích của Nguyên Mông bị bắt trong trận này), tiếp theo đó các vua Trần đem binh tới ác chiến, đập tan nát quân Nguyên. Tiếp theo đó, quân Trần mai phục hai bên cũng dũng vũ xông ra, tiếp tục diệt tan quân địch. Khi nước triều rút, quân Nguyên hoàn toàn lâm vào thảm họa. Với sự hoàn tất sứ mệnh phá hủy đoàn binh thuyền của Ô Mã Nhi, toàn thắng này dẫn đến thắng lợi hoàn toàn của Đại Việt trong cuộc Chiến tranh Nguyên Mông–Đại Việt lần 3 và hoàn toàn phá tan âm mưu xâm chiếm Đại Việt của nhà Nguyên. Chiến tích vẻ vang này của Trần Hưng Đạo cùng với hai vị minh quân triều Trần đã lưu danh trong lịch sử Việt Nam, và là đề tài cho nhiều tác phẩm văn học Việt Nam thời Trung đại, dưới ngòi bút của các danh sĩ Trương Hán Siêu, Nguyễn Trãi,... Trương Hán Siêu đã thuật lại diễn biến cuộc chiến này trong bài Phú sông Bạch Đằng như sau: "Thuyền bè muôn đội, tinh kỳ phấp phới/Hùng hổ sáu quân, giáo gươm sáng chói/[...]/Trận đánh được thua chửa phân/Chiến lũy bắc nam chống đối/[...]/Tất Liệt thế cường, Lưu Cung chước dối/Những tưởng gieo roi một lần/Quét sạch Nam bang bốn cõi/[...]/Tr ... [ĐÃ CẮT BỚT]

[hf_wikipedia_trận_bạch_đằng_1288_0001_11581a43ec9d] Trận Bạch Đằng (1288)
định tổ chức rút về Trung Quốc theo nhiều hướng khác nhau. Ngày 3 tháng 3 năm Mậu Tí (1288), Hữu thừa Trình Bằng Phi, Thiên tỉnh Đạt Mộc thống lĩnh kị binh đi đón các cánh quân di chuyển bằng đường thủy (đoàn thuyền của Trương Văn Hổ). Tuy nhiên khi qua chợ Đông-Hồ thì bị dòng sông chắn ngang, phải quay lại, nhưng cầu cống đã bị quân nhà Trần bám theo sau phá hủy. Quân Nguyên rơi vào thế nguy, trước mặt thì bị quân Trần chặn đường, sau lưng là chướng ngại thiên nhiên. Tuy nhiên quân Nguyên do tra hỏi những tù binh nên đã tìm được đường thoát, nửa đêm hôm đó cánh quân này đột phá vòng vây chạy trốn theo con đường khác, phối hợp với một cánh quân Nguyên đang rút lui để cùng nhau ra khỏi ải Nội Bàng. Tuy bị bất ngờ bởi sự thay đổi lộ trình của quân Nguyên, quân đội nhà Trần đuổi theo đánh rất sát vào cánh quân đoạn hậu. Tướng Nguyên là Vạn hộ Đáp Thứ Xích và Lưu Thế Anh phải dẫn quân quay trở lại phía sau đối phó với quân Trần, sau một trận giao chiến bắt được và giết các tướng Trần chỉ huy toán quân tập kích là các tướng Phạm Trù và Nguyễn Kị. Ngày 7 tháng 3 năm Mậu Tý (8 tháng 4 năm 1288), cánh quân Mông Cổ rút bằng đường thủy đi tới động Trúc (nay thuộc Thủy Nguyên), tại đây họ bị quân nhà Trần chặn đánh, nhưng tướng Nguyên là Lư Khuê chỉ huy quân này đánh lui quân nhà Trần và chiếm được 20 thuyền chiến. Ngày 8 tháng 3 (9 tháng 4 năm 1288), Ô Mã Nhi không cho quân rút về bằng đường biển mà đi theo sông Bạch Đằng, vì tính rằng đường biển đã bị thủy quân nhà Trần vây chặt thì phòng bị đường sông có thể sơ hở, hơn nữa sông Bạch Đằng nối liền với nội địa Trung Quốc bằng thủy lộ, thuận lợi cho việc rút lui. Năm 1288, sau khi rút lui khỏi kinh đô Thăng Long, Trần Hưng Đạo đã quyết định đánh một trận lớn chống quân Mông Cổ xâm lược đi vào Đại Việt thông qua sông Bạch Đằng. Sông Bạch Đằng trước đó cũng là một địa danh lịch sử khi Ngô Quyền đã từng đánh thắng quân Nam Hán trong năm 938, kết thúc gần 1000 năm Bắc thuộc. Trần Hưng Đạo đã nghiên cứu kỹ lưỡng quy luật thủy triều của con sông này để vạch ra thế trận cọc để mai phục quân Mông Nguyên Trần Hưng Đạo chỉ huy quân dân Đại Việt chuẩn bị một trận địa mai phục lớn trên sông Bạch Đằng, là nơi đoàn thuyền của quân Nguyê ... [ĐÃ CẮT BỚT]

------------------------------------------------------------------------------------------------------------------------
ROLE: assistant
------------------------------------------------------------------------------------------------------------------------
Nguồn được dùng: [hf_wikipedia_ngô_quyền_0000_af223d790816]

Trả lời:
Chiến thắng Bạch Đằng năm 938 gắn với Ngô Quyền. Tài liệu nêu rằng năm 938, ông lãnh đạo nhân dân đánh bại quân Nam Hán trong trận Bạch Đằng.

In [7]:
df_msg["type"].value_counts()
type_counts = df_msg["type"].value_counts()
type_percent = (type_counts / len(df_msg) * 100).round(2)

summary_df = pd.DataFrame({
    "count": type_counts,
    "percent": type_percent,
})

display(summary_df)

                      count  percent
type
noisy_context            13     65.0
grounded_qa               4     20.0
insufficient_context      2     10.0
false_premise             1      5.0

In [9]:
def simple_format_chat(messages):
    parts = []

    for m in messages:
        role = m["role"]
        content = m["content"]

        if role == "system":
            parts.append(f"<system>\n{content}\n</system>")
        elif role == "user":
            parts.append(f"<user>\n{content}\n</user>")
        elif role == "assistant":
            parts.append(f"<assistant>\n{content}\n</assistant>")

    return "\n\n".join(parts)

idx = 0

formatted = simple_format_chat(records[idx]["messages"])

print(formatted[:4000])

<user>
Câu hỏi:
Chiến thắng Bạch Đằng năm 938 gắn với nhân vật nào?

Tài liệu tham khảo:
[hf_wikipedia_ngô_quyền_0000_af223d790816] Ngô Quyền
Ngô Quyền (; 17 tháng 4 năm 898 – 14 tháng 2 năm 944), còn được biết đến với tên gọi Tiền Ngô Vương () là vị vua đầu tiên của nhà Ngô trong lịch sử Việt Nam. Năm 938, ông là người lãnh đạo nhân dân đánh bại quân Nam Hán trong trận Bạch Đằng, chính thức kết thúc gần một ngàn năm Bắc thuộc, mở ra một thời kì độc lập lâu dài của Việt Nam. Sau chiến thắng này, ông lên ngôi vua, lập ra nhà Ngô, trị vì từ năm 939 đến năm 944. Ngô Quyền nằm trong danh sách mười bốn anh hùng dân tộc Việt Nam. Phan Bội Châu xem ông là vị Tổ Trung hưng của Việt Nam. Thân thế Ngô Quyền sinh ngày 12 tháng 3 năm Đinh Tỵ (17 tháng 4 năm 898) trong một dòng họ hào trưởng có thế lực. Cha là Ngô Mân làm chức châu mục Đường Lâm. Ngô Quyền được sử sách mô tả là bậc anh hùng tuấn kiệt, "có trí dũng". Theo Đại Việt Sử ký Toàn thư: Sự nghiệp Bối cảnh Thời bấy giờ nhà Đường ở Trung Quốc cai trị nước Việt. Từ giữa thế kỷ IX, nhà Đường phải đối phó với hai biến cố lớn là nông dân khởi nghĩa và phiên trấn cát cứ. Năm 907, nhà Đường mất, Chu Ôn lập nên nhà Hậu Lương, bắt đầu cuộc loạn Ngũ Đại, sử Trung Quốc gọi là Ngũ đại Thập quốc. Ở miền Nam Trung Quốc, Tiết độ sứ Quảng Châu là Lưu Nham đã cát cứ và dựng nước Nam Hán. Năm 905, nhân việc nhà Đường có loạn, một thổ hào người Việt là Khúc Thừa Dụ nổi lên đánh đuổi người Trung Quốc, chiếm giữ phủ thành, xưng là Tiết độ sứ. Năm 907, Khúc Thừa Dụ chết, con là Khúc Hạo lên thay. Khúc Hạo sai con là Khúc Thừa Mỹ làm Hoan hảo sứ sang dò xét nhà Nam Hán. Năm 917, Khúc Hạo chết, Khúc Thừa Mỹ lên thay, cho người sang nhà Lương lĩnh tiết việt, muốn lợi dụng sự mâu thuẫn giữa nước Lương và Nam Hán để củng cố sự nghiệp tự cường của mình. Vua Nam Hán là Lưu Cung tức giận, xua quân chiếm cứ Giao Chỉ. Năm 930, tướng Nam Hán Lý Khắc Chính đem binh đánh, bắt được Khúc Thừa Mỹ, Lý Khắc Chính lưu lại Giao Chỉ. Một hào trưởng người Ái Châu (thuộc Thanh Hóa ngày nay) là Dương Đình Nghệ nuôi 3000 con nuôi, mưu đồ khôi phục. Ngô Quyền lớn lên làm nha tướng cho Dương Đình Nghệ, được Dương Đình Nghệ gả con gái cho và giao quyền cai quản Ái châu, đất bản bộ của họ Dương. Năm 931, Dương Đình Nghệ phát binh từ Thanh Hóa ra Bắc đánh đuổi quân Nam Hán, đánh bại Lý Tiến và quân cứu viện ... [ĐÃ CẮT BỚT]

[hf_wikipedia_trận_bạch_đằng_1288_0000_9e0fa2aca313] Trận Bạch Đằng (1288)
Trận Bạch Đằng năm 1288 xảy ra trên sông Bạch Đằng thuộc đất Đại Việt, là một trận đánh quan trọng trong các cuộc kháng chiến chống Nguyên Mông trong lịch sử Việt Nam. Đây là chiến thắng vẻ vang của quân Đại Việt do Quốc công Tiết chế Trần Hưng Đạo cùng với Thái thượng hoàng Trần Thánh Tông và vua Trần Nhân Tông chỉ huy trước quân xâm lược Nguyên Mông. Quân Nguyên bị thiệt hại vô cùng nặng (với khoảng hơn 4 vạn quân sĩ bị loại khỏi vòng chiến), và nhiều tướng Nguyên trong đó có cả Ô Mã Nhi, Phạm Nhàn và Phàn Tiếp cũng bị bắt sống và dâng lên Thượng hoàng Thánh Tông. Ngoài ra, có những 400 chiến thuyền của quân Nguyên rơi vào tay quân Trần. Đại thắng trên sông Bạch Đằng được xem là trận thủy chiến lớn nhất trong lịch sử Việt Nam, và là thắng lợi tiêu biểu nhất của Đại Việt trong ba cuộc kháng chiến chống quân xâm lược Nguyên-Mông. Đại thắng này là một chiến quả của kế cắm cọc trên sông Bạch Đằng của Hưng Đạo Vương, mở đầu với việc quân sĩ của ông lừa được địch vào trận địa cọc nhân triều rút. Quân Nguyên vấp phải sự chiến đấu mãnh liệt của quân Thánh Dực dưới quyền Nguyễn Khoái (Bình chương Áo Lỗ Xích của Nguyên Mông bị bắt trong trận này), tiếp theo đó các vua Trần đem binh tới ác chiến, đập tan nát quân Nguyên. Tiếp theo đó, quân Trần mai phục hai bên cũng dũng vũ xông ra, tiếp tục diệt tan quân địch. Khi nước triều rút, quân Nguyên hoàn toàn lâm vào thảm họa. Với sự hoàn tất sứ mệnh phá hủy đoàn binh thuyền của Ô Mã Nhi, toàn thắng này dẫn đến thắng lợi hoàn toàn của Đại Việt trong cuộc Chiến tranh Nguyên Mông–Đại Việt lần 3 và hoàn toà

In [10]:
length_rows = []

for r in records:
    user_text = ""
    assistant_text = ""

    for m in r["messages"]:
        if m["role"] == "user":
            user_text += m["content"]
        elif m["role"] == "assistant":
            assistant_text += m["content"]

    length_rows.append({
        "id": r.get("id", ""),
        "type": r.get("type", ""),
        "user_chars": len(user_text),
        "assistant_chars": len(assistant_text),
        "user_words": len(user_text.split()),
        "assistant_words": len(assistant_text.split()),
    })

df_len = pd.DataFrame(length_rows)

display(df_len)
display(df_len.describe())

,id,type,user_chars,assistant_chars,user_words,assistant_words
0,sample_0001,noisy_context,6940,211,1464,36
1,sample_0002,noisy_context,6914,195,1467,24
2,sample_0003,noisy_context,6922,197,1489,35
3,sample_0004,noisy_context,6928,169,1468,29
4,sample_0005,noisy_context,6957,240,1503,45
5,sample_0006,noisy_context,6931,274,1461,51
6,sample_0007,noisy_context,6928,211,1460,36
7,sample_0008,noisy_context,6906,196,1510,26
8,sample_0009,noisy_context,6909,352,1520,73
9,sample_0010,noisy_context,6911,265,1465,44
10,sample_0011,noisy_context,6948,268,1474,38
11,sample_0012,noisy_context,6986,285,1473,49
12,sample_0013,noisy_context,6931,336,1468,56
13,sample_0014,grounded_qa,2355,155,517,26
14,sample_0015,grounded_qa,2345,143,514,23
15,sample_0016,grounded_qa,2360,200,518,34
16,sample_0017,grounded_qa,2346,148,508,23
17,sample_0018,insufficient_context,4630,249,1019,53
18,sample_0019,insufficient_context,4639,216,1000,48
19,sample_0020,false_premise,6938,363,1472,50

        user_chars  assistant_chars   user_words  assistant_words
count    20.000000        20.000000    20.000000        20.000000
mean   5786.200000       233.650000  1238.500000        39.950000
std    1895.007002        65.115505   398.165993        13.307991
min    2345.000000       143.000000   508.000000        23.000000
25%    4636.750000       195.750000  1014.250000        28.250000
50%    6918.000000       213.500000  1466.000000        37.000000
75%    6932.750000       269.500000  1473.250000        49.250000
max    6986.000000       363.000000  1520.000000        73.000000